export enum ListActionsNames {
  FETCH_LIST_REQUEST = 'FETCH_LIST_REQUEST',
  FETCH_LIST_SUCCESS = 'FETCH_LIST_SUCCESS',
  FETCH_LIST_REJECTED = 'FETCH_LIST_REJECTED',

  CLEAR_LIST = 'CLEAR_LIST',

  FETCH_LIST_ITEM_REQUEST = 'FETCH_LIST_ITEM_REQUEST',
  FETCH_LIST_ITEM_SUCCESS = 'FETCH_LIST_ITEM_SUCCESS',
  FETCH_LIST_ITEM_REJECTED = 'FETCH_LIST_ITEM_REJECTED',

  CLEAR_CURRENT_LIST_ITEM = 'CLEAR_CURRENT_LIST_ITEM',
}

export default ListActionsNames;
